export enum Types {
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  MULTIPLE_RESPONSE = 'MULTIPLE_RESPONSE',
  TRUE_FALSE = 'TRUE_FALSE',
  SHORT_RESPONSE = 'SHORT_RESPONSE',
  FILL_EMPTY_FIELDS = 'FILL_EMPTY_FIELDS',
  CORRESPONDANCE = 'CORRESPONDANCE',
  SEQUENCING = 'SEQUENCING',
  HOTSPOT = 'HOTSPOT',
  DRAG_DROP = 'DRAG_DROP',
  DRAG_WORDS = 'DRAG_WORDS',
  SELECT_FROM_LIST = 'SELECT_FROM_LIST',
  NUMERIC = 'NUMERIC',
  LIKERT_SCALE = 'LIKERT_SCALE',
  WRITING = 'WRITING',
  WORD_COLORATION = 'WORD_COLORATION',
  LINK_ARROW = 'LINK_ARROW'
}
