import { Injectable } from '@angular/core';
import { BehaviorSubject, map } from 'rxjs';
import { Club, ClubMinimized } from '../model/Club';
import { ClubFeeds } from '../model/Club_Feeds';
import { MinimizedUser } from '../model/User';
import { ChatHistory } from '../model/Chat_History';

@Injectable({
  providedIn: 'root'
})
export class ClubService {
  clubsContent: BehaviorSubject<Club[]> = new BehaviorSubject<Club[]>(null);
  clubFeedsContent: BehaviorSubject<ClubFeeds[]> = new BehaviorSubject<ClubFeeds[]>(null);
  minimizedUserContent: BehaviorSubject<MinimizedUser[]> = new BehaviorSubject<MinimizedUser[]>(null);
  messagesContent: BehaviorSubject<ChatHistory[]> = new BehaviorSubject<ChatHistory[]>(null);

  getMinimizedUsers() {
    return this.minimizedUserContent;
  }
  getMessagesList(user_id: number, friend_id: number) {
    return this.messagesContent.pipe(
      map((messages) => {
        return messages.filter((message) => {
          return message.chat_sender.user_id === user_id && message.chat_receiver.user_id === friend_id;
        });
      })
    );
  }

  getClubById(id: number) {
    return this.clubsContent.pipe(map((clubs) => {}));
  }

  getClubs() {
    return this.clubsContent;
  }

  getClubFeeds() {
    return this.clubFeedsContent;
  }

  randomDate(start, end) {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  }

  constructor() {
    this.clubsContent.next([
      {
        club_id: 1,
        description: 'Club de robotique',
        numberOfParticipants: 10,
        name: 'Robotic Club',
        logo: 'https://static.remove.bg/remove-bg-web/f9c9a2813e0321c04d66062f8cca92aedbefced7/assets/start_remove-c851bdf8d3127a24e2d137a55b1b427378cd17385b01aec6e59d5d4b5f39d2ec.png'
      },
      {
        club_id: 2,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Puzzle Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/993/993723.png'
      },
      {
        club_id: 3,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Swimming Club',
        logo: 'https://cdn-icons.flaticon.com/png/512/2371/premium/2371508.png?token=exp=1660601560~hmac=77724061c1f2afaa4c15c12aebdd4b93'
      },
      {
        club_id: 4,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Fight Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/2405/2405298.png'
      },
      {
        club_id: 5,
        description: 'Club de football',
        numberOfParticipants: 10,

        name: 'Exchange Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/4727/4727330.png'
      },
      {
        club_id: 6,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Idea Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/8189/8189702.png'
      },
      {
        club_id: 7,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Brain Storm Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/8189/8189904.png'
      },
      {
        club_id: 8,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Family Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/2755/2755465.png'
      },
      {
        club_id: 9,
        description: 'Club de football',
        numberOfParticipants: 10,
        name: 'Chess Club',
        logo: 'https://cdn-icons-png.flaticon.com/512/4072/4072149.png'
      }
    ]);
    this.clubFeedsContent.next([
      {
        feed_id: '2',
        poster: 'jilani Ourari',
        poster_image: 'https://cdn-icons-png.flaticon.com/512/2755/2755465.png',
        type: 'Image',
        description: 'this post was generated by   the system',
        date: this.randomDate(new Date(2012, 0, 1), new Date()),
        post: 'https://static.remove.bg/remove-bg-web/f9c9a2813e0321c04d66062f8cca92aedbefced7/assets/start_remove-c851bdf8d3127a24e2d137a55b1b427378cd17385b01aec6e59d5d4b5f39d2ec.png',
        comments: [
          {
            comment: 'this is a comment',
            commenter: 'John Doe',
            commenter_id: '1',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Temer Hosni',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Ourari Mohamed',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Oussema Bedoui',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Saif Mekki',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Anis Ben Amor',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          }
        ]
      },
      {
        feed_id: '1',
        poster: 'Ahmed Ourari',
        poster_image: 'https://cdn-icons-png.flaticon.com/512/2755/2755465.png',
        type: 'Video',
        description: 'this post was generated by the system',
        date: this.randomDate(new Date(2012, 0, 1), new Date()),
        post: 'https://www.youtube.com/embed/_ciasFtwkRU',
        comments: [
          {
            comment: 'this is a comment',
            commenter: 'John Doe',
            commenter_id: '1',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Temer Hosni',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Ourari Mohamed',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Oussema Bedoui',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Saif Mekki',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Anis Ben Amor',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          }
        ]
      },
      {
        feed_id: '3',
        poster: 'lotfi Mehrzi',
        poster_image: 'https://cdn-icons-png.flaticon.com/512/2755/2755465.png',
        type: 'Text',
        description: 'this post was generated by the system',
        date: this.randomDate(new Date(2012, 0, 1), new Date()),
        post: 'https://www.youtube.com/embed/_ciasFtwkRU',
        comments: [
          {
            comment: 'this is a comment',
            commenter: 'John Doe',
            commenter_id: '1',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Temer Hosni',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Ourari Mohamed',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Oussema Bedoui',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Saif Mekki',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          },
          {
            comment: 'this is a comment',
            commenter: 'Anis Ben Amor',
            commenter_id: '2',
            commenter_image: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
          }
        ]
      }
    ]);
    this.minimizedUserContent.next([
      {
        user_id: 1,
        name: 'John Doe',
        photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
      },
      {
        user_id: 2,
        name: 'Jane Doe',
        photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
      },
      {
        user_id: 3,
        name: 'jilani ourari',
        photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
      }
    ]);

    this.messagesContent.next([
      {
        chat_id: 1,
        chat_history_type: 'text',
        chat_history_date: new Date(),
        chat_sender: {
          user_id: 1,
          name: 'John Doe',
          photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
        },
        chat_receiver: {
          user_id: 2,
          name: 'Jane Doe',
          photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
        },
        message: {
          message_id: 1,
          message_type: 'text',
          content: 'Hello',
          message_timing: new Date()
        }
      },
      {
        chat_id: 2,
        chat_history_type: 'text',
        chat_history_date: new Date(),
        chat_sender: {
          user_id: 2,
          name: 'Jane Doe',
          photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
        },
        chat_receiver: {
          user_id: 1,
          name: 'John Doe',
          photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
        },
        message: {
          message_id: 2,
          message_type: 'text',
          content: 'Hello',
          message_timing: new Date()
        }
      },
      {
        chat_id: 3,
        chat_history_type: 'text',
        chat_history_date: new Date(),
        chat_sender: {
          user_id: 1,
          name: 'Jane Doe',
          photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
        },
        chat_receiver: {
          user_id: 2,
          name: 'John Doe',
          photo: 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
        },
        message: {
          message_id: 3,
          message_type: 'text',
          content: 'How are you?',
          message_timing: new Date()
        }
      }
    ]);
  }
}
